"""Typed schemas for Jev decisions (PROMPT sections 9, 10, 13).

Jev answers *typed* questions; these enums and dataclasses are the application
side of that contract. Jev never generates prose, coordinates, or code — it
picks an operation, picks a candidate id, and returns calibrated probabilities.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class Operation(str, Enum):
    """The bounded set of operations Jev can choose (PROMPT sections 10, 13)."""

    CLICK = "CLICK"
    DOUBLE_CLICK = "DOUBLE_CLICK"
    RIGHT_CLICK = "RIGHT_CLICK"
    TYPE = "TYPE"
    PRESS_KEY = "PRESS_KEY"
    SCROLL = "SCROLL"
    DRAG = "DRAG"
    WAIT = "WAIT"
    DONE = "DONE"
    BLOCKED = "BLOCKED"

    @property
    def needs_target(self) -> bool:
        return self in {
            Operation.CLICK,
            Operation.DOUBLE_CLICK,
            Operation.RIGHT_CLICK,
            Operation.DRAG,
        }

    @property
    def needs_text(self) -> bool:
        return self in {Operation.TYPE, Operation.PRESS_KEY}

    @property
    def is_terminal(self) -> bool:
        return self in {Operation.DONE, Operation.BLOCKED}


# Human-readable operation policy sent to Jev as the Choice criteria. The
# question descriptions ARE the policy (PROMPT section 10).
OPERATION_CRITERIA: dict[str, str] = {
    Operation.CLICK.value: "Activate the selected visible interactive element (button, link, tab, menu item).",
    Operation.DOUBLE_CLICK.value: "Double-click the selected element, e.g. to open a file or item.",
    Operation.RIGHT_CLICK.value: "Open the context menu for the selected element.",
    Operation.TYPE.value: "Insert text into the currently focused editable element.",
    Operation.PRESS_KEY.value: "Send a keyboard key or shortcut required by the task, e.g. Return or ctrl+l.",
    Operation.SCROLL.value: "Scroll the current view because the desired target is outside the visible region.",
    Operation.DRAG.value: "Drag the selected source element onto a target element.",
    Operation.WAIT.value: "Wait because the UI is loading or changing and acting now would be premature.",
    Operation.DONE.value: "The user's requested goal has been verified as complete.",
    Operation.BLOCKED.value: "The task cannot be grounded safely or cannot continue.",
}


@dataclass
class Decision:
    """A single resolved decision returned by the engine.

    ``target_id`` refers to a candidate id (or ``None``). ``text`` carries the
    key/text argument for TYPE/PRESS_KEY, which is chosen by deterministic code
    or the planner, never generated by Jev.
    """

    operation: Operation
    target_id: int | None
    text: str | None
    confidence: float
    should_continue: bool
    safe: bool
    # Raw probabilities/telemetry for logging and the debug panel.
    op_probabilities: dict[str, float]
    model: str = ""
    input_tokens: int = 0
    latency_ms: float = 0.0

    def describe(self) -> str:
        bits = [self.operation.value]
        if self.target_id is not None:
            bits.append(f"→ #{self.target_id}")
        if self.text:
            bits.append(f'"{self.text}"')
        bits.append(f"({self.confidence:.0%})")
        return " ".join(bits)
